### ISSUE TITLE
Docker images: Not all containers up and running

### ISSUE THREAD

**Issue by olimination** [maoo/alfresco-boxes#39]
I use the Docker run scripts docker/scripts/run/community.sh for testing Alfresco Community AllInOne on CentOS7.
But I cannot login to HOST:8080/share, it says "Your authentication details have not been recognized or Alfresco may not be available at this time."

I guess this is because not all Docker containers are up and running, see my docker ps -a command output:

```
d72d25a01bcd        maoo/alfresco-allinone-community:latest   "/bin/sh -c '/etc/in   2 minutes ago       Up 2 minutes               0.0.0.0:8080->8080/tcp             alf1                
c2e339e42f1d        orchardup/mysql:latest                    "/usr/local/bin/run"   2 minutes ago       Up 2 minutes               3306/tcp                           db                  
89ebac547861        ubuntu:12.04                              "/bin/sh -c 'chmod -   2 minutes ago       Exited (1) 2 minutes ago                                      data                
31faffdee064        crosbymichael/skydock:latest              "/go/bin/skydock -tt   2 minutes ago       Exited (1) 2 minutes ago                                      skydock             
f049a50f9888        crosbymichael/skydns:latest               "skydns -http 0.0.0.   2 minutes ago       Up 2 minutes               MY_IP:53->53/udp, 8080/tcp   skydns
```

Do you have any idea why this is so?
Any hints how to debug?

Thanks for help :)!

**Comment by maoo** [comment]
Hi @olimination ,
your `docker ps` looks nice; I expect that they're all running; FTR, you don't need "ubuntu:12.04".

You're currently running an allinone (as you can see from first line of the ps command) therefore all alfresco logic should be in there.

The error behind the message you see could be any; I'd advise you to run the allinone Docker container in interactive mode, so that you can log into the box and check alfresco.log, catalina.out etc

Replace line https://github.com/maoo/alfresco-boxes/blob/master/docker/scripts/run/community.sh#L22 with line https://github.com/maoo/alfresco-boxes/blob/master/docker/scripts/run/community.sh#L25

HTH
  mao

**Comment by olimination** [comment]
Thanks for feedback.

My assumption was that "skydock" container needs to run, because on my local machine it works, the "skydock" container is running. But on my separate server the "skydock" container does not run. That's why I assumed that this could be the issue.

But I will run the container in interactive mode and check the logs.

**Comment by maoo** [comment]
Yes, `skydock` must run, otherwise you won't have a DNS server that resolves your hosts; though I see skydock in your container list, so I thought it was running.

**Comment by olimination** [comment]
ah ok, so skydock needs to run, but the "data" container not necessarily as you stated above. You can scroll horizontally so you see also the status of my posted "docker ps -a" output.

Then I need to check why skydock exited...

**Comment by olimination** [comment]
I haven't figured out yet the issue with the skydock container start, but I guess its some network configuration issue on my server (firewalld, etc.).

I have now created Alfresco Docker images by my own without using skydock&Co. because I just used then Container linking functionality. So I have now 3 images:
- alf1 -> Alfresco app
- alf1_data -> Docker data volume for alf_data
- db_pg -> A Postgres database

this worked then :).

**Comment by maoo** [comment]
Very glad you found the solution. I used Container linking in the past, but decided to use a more generic approach, since Container linking didnt allow me to have bi-directional pointers (a points to b AND b points to a), therefore having - for example - Alfresco pointing to Solr and the other way around was not doable.

Maybe new versions of Docker have solved this issue?

Thx again for the great feedback!
